Added UFO QC Ratio Check filter - try 3
NOAA-EMC/ufo pull request #29
Opened 2020-12-11 17:45 UTC by ilianagenkova

Description

This branch adds a UFO QC Ratio Check filter (JEDI Academy Dec 2020, Practical #7 Homework)
It calculates the ratio between two variables and checks if it's within a specified range (See: testinput/qc_ratiocheck.yaml)
Definition of Done

Passing test_ufo_qc_gen_ratiocheck
Issue(s) addressed

No issue was opened for this PR.
Dependencies

N/A
Impact

Shows my ability to add a simple UFO QC Filter

Note: ctest passed page ~25

2020-12-11 17:48 UTC, aerorahul commented on src/ufo/filters/RatioCheck.cc
> +//Cory's     if (val[jobs] == missing || ref[jobs] == missing || ref[jobs] == 0.0) {
we also should check if the denominator is zero to trap divide by zero failures.

2020-12-11 17:49 UTC, aerorahul commented on src/ufo/filters/RatioCheck.cc
> +//Cory's     if (val[jobs] == missing || ref[jobs] == missing || ref[jobs] == 0.0) {
and flag it.

2020-12-11 17:50 UTC, aerorahul commented on src/ufo/filters/RatioCheck.cc
> +        float ratio = val[jobs] / ref[jobs];
This does not flag it as rejected, just does not apply the ratio filter.

2020-12-11 17:50 UTC, aerorahul commented on src/ufo/filters/RatioCheck.cc
> +        } //Iliana's
Indentation is overloaded.

2020-12-11 17:51 UTC, aerorahul requested changes
see inline comments.

2020-12-11 18:22 UTC, ilianagenkova commented
@aerorahul Do I need to resolve these conflicts? I "git add"-ed these files, and I saw no issues from the command line, not sure how far down the rabbit hole do you want us to go with this homework...

"This branch has conflicts that must be resolved

Conflicting files
src/ufo/filters/QCflags.h
src/ufo/filters/QCmanager.cc"

2020-12-11 18:31 UTC, ilianagenkova commented
@CoryMartin-NOAA thanks! I won't be merging then. The Practical #7 instruction had a section in Red, telling to just  push. 
Shall I consider this homework assignment completed? :)

2020-12-11 19:43 UTC, CoryMartin-NOAA requested changes

2020-12-11 19:43 UTC, CoryMartin-NOAA commented on src/ufo/filters/RatioCheck.cc
> +        float ratio = val[jobs] / ref[jobs];
To clarify, this means that by default, if ref is zero, it passes QC.

2020-12-11 19:43 UTC, CoryMartin-NOAA commented on test/testinput/qc_ratiocheck.yaml
> +      obsfile: /scratch1/NCEPDEV/da/Iliana.Genkova/JEDI/tutorial/src/fv3-bundle/ufo/test/testinput/filters/filters_testdata.nc4
No hard coded paths!

2020-12-11 20:34 UTC, ilianagenkova commented on test/testinput/qc_ratiocheck.yaml
> +      obsfile: /scratch1/NCEPDEV/da/Iliana.Genkova/JEDI/tutorial/src/fv3-bundle/ufo/test/testinput/filters/filters_testdata.nc4
What is the explicit path equivalent to /Data/file_name ?

2020-12-14 21:45 UTC, ilianagenkova commented on src/ufo/filters/RatioCheck.cc
> +//Cory's     if (val[jobs] == missing || ref[jobs] == missing || ref[jobs] == 0.0) {
Got it!

2020-12-14 21:45 UTC, ilianagenkova commented on src/ufo/filters/RatioCheck.cc
> +        } //Iliana's
ufo_coding_norms passed

2020-12-14 21:48 UTC, ilianagenkova commented on test/testinput/qc_ratiocheck.yaml
> +      obsfile: /scratch1/NCEPDEV/da/Iliana.Genkova/JEDI/tutorial/src/fv3-bundle/ufo/test/testinput/filters/filters_testdata.nc4
@CoryMartin-NOAA Thursday's slides say _component/test/Data_ is the relative path to test data. I tried a couple of ways to replace the explicit path, with no success. 
If my obs files have explicit path:
/scratch1/NCEPDEV/da/Iliana.Genkova/JEDI/tutorial/src/fv3-bundle/ufo/test/testinput/filters/filters_testdata.nc4
what would it be the Data/.... version of it?

2020-12-14 21:54 UTC, CoryMartin-NOAA commented on test/testinput/qc_ratiocheck.yaml
> +      obsfile: /scratch1/NCEPDEV/da/Iliana.Genkova/JEDI/tutorial/src/fv3-bundle/ufo/test/testinput/filters/filters_testdata.nc4
@ilianagenkova the path should be:
```
Data/ufo/testinput_tier_1/filters_testdata.nc4
```
It's the relative path from the build/COMPONENT/test/ directory

2021-01-15 16:44 UTC, closed without merging