Added in UFO QC Ratio Check
NOAA-EMC/ufo pull request #5
Opened 2020-12-10 22:43 UTC by nicholasesposito

2020-12-10 22:57 UTC, aerorahul commented
@nicholasesposito 
Please resolve the conflicts
Please discard changes to the amsua and cris yaml files.  They should not have been touched.
Please attached screenshot of passing tests.

2020-12-11 01:13 UTC, emilyhcliu requested changes
@nicholasesposito You have the following three files which would not be changed for this PR:
cris_qc_filters.yaml
amsua_qc.yaml
airs_qc_filters.yaml

So, please reset the changes to the originals from your feature branch, and then commit again.

Your changes related to the HW assignment look good!

2020-12-11 12:55 UTC, CoryMartin-NOAA requested changes

2020-12-11 12:55 UTC, CoryMartin-NOAA commented on src/ufo/filters/QCmanager.cc
> +//           ignss + idiffref + iseaice + itrack + ibuddy + idydx == iobs);  //  orig
git tracks changes so no need to keep the original line commented out

2020-12-11 12:55 UTC, CoryMartin-NOAA commented on src/ufo/filters/RatioCheck.cc
> +// check for threshold and if exists, set vmin and vmax appropriately
Fine for now, but for a real pull request, remove instead of comment out.

2020-12-11 12:55 UTC, CoryMartin-NOAA commented on test/testinput/airs_qc_filters.yaml
> +#    minvalue: 50.00001
This file, and the next 2 should not be modified

2020-12-11 18:58 UTC, nicholasesposito commented on src/ufo/filters/QCmanager.cc
> +//           ignss + idiffref + iseaice + itrack + ibuddy + idydx == iobs);  //  orig
I put comments in so if I wanted to go back and see what the changes made were, I could

2020-12-11 18:58 UTC, nicholasesposito commented on src/ufo/filters/QCmanager.cc
> +//           ignss + idiffref + iseaice + itrack + ibuddy + idydx == iobs);  //  orig
Or rather, explanations

2020-12-11 21:10 UTC, nicholasesposito commented
How would I discard the changes to the amsua_qc, etc files? I tried to check them out again, but that doesn't appear to change anything.

2020-12-11 21:12 UTC, aerorahul commented
`git checkout -- test/testinput/amsua_qc.yaml`

2020-12-11 21:15 UTC, nicholasesposito commented
![ratiocheck](https://user-images.githubusercontent.com/62616739/101955570-0d73eb80-3bcc-11eb-8dc7-cb7b33d42756.png)
The attached image is the confirmation that ratiocheck worked. The image is also in the powerpoint for homework 4

2020-12-11 21:17 UTC, nicholasesposito commented
Do I need to 'git add' the newly checked out files? When I do, 'git status' says there is nothing to commit, ad the working tree is clean.

2020-12-11 21:25 UTC, CoryMartin-NOAA commented
I'm not convinced "-- "will work I think you need to grab them from develop. Because it was already committed. But not sure.
```
git checkout develop -- test/testinput/amsua_qc.yaml
```

2020-12-11 21:26 UTC, nicholasesposito commented
[Nicholas.Esposito@hfe04 ufo]$ git checkout develop -- test/testinput/amsua_qc.yaml
fatal: invalid reference: develop

2020-12-11 21:29 UTC, aerorahul commented
@nicholasesposito instead of back and forth, 
Google: "how to revert a file to previous commit git"
Chances are 1st hit will resolve your issue.

2020-12-17 15:57 UTC, nicholasesposito commented
I updated the files, committed, and re-pushed it. Not sure if it is coming up.

2020-12-17 16:00 UTC, CoryMartin-NOAA reviewed
@nicholasesposito changes look good, no extra files, etc. However, like I said before, you normally won't want to keep things commented out to keep the original lines, git keeps records of each version so you can always go back and see what it was like before you made these changes, but it's okay this one time for learning.

2021-01-15 16:43 UTC, closed without merging