Feature/tutorial louis
NOAA-EMC/ufo pull request #7
Opened 2020-12-10 23:03 UTC by LouisKouvaris-NOAA

[screenshot.txt](https://github.com/NOAA-EMC/ufo/files/5676133/screenshot.txt)

2020-12-10 23:04 UTC, aerorahul commented
@LouisKouvaris-NOAA 
You need to ask for review, not assign.

2020-12-10 23:04 UTC, aerorahul commented on Testing/Temporary/CTestCostData.txt
> +---
Please don't include files that are not part of the code.

2020-12-10 23:04 UTC, aerorahul commented on Testing/Temporary/LastTest.log
> +Start testing: Dec 10 21:10 UTC
This is a log and should not be commited.

2020-12-10 23:05 UTC, aerorahul commented on src/ufo/filters/RatioCheck.cc
> +      if (val[jobs] == missing || ref[jobs] == missing || abs(ref[jobs]) < 1.e-36) {
abs will make this into an integer.

2020-12-10 23:06 UTC, aerorahul commented on test/testinput/cris_qc_filters.yaml
> +#   maxvalue: 449.99999
why was this file changed?

2020-12-10 23:07 UTC, aerorahul commented
Please include a screenshot of the passing/failing tests.

2020-12-11 00:37 UTC, emilyhcliu commented on test/testinput/cris_qc_filters.yaml
> +# passedBenchmark: 402   #(m_unittest)
@LouisKouvaris-NOAA /test/testinput/cris_qc_filters.yaml should not be changed here.  Please go to the testinput directory and do:
git checkout  -- cris_qc_filters.yaml

2020-12-11 12:53 UTC, CoryMartin-NOAA requested changes

2020-12-11 12:53 UTC, CoryMartin-NOAA commented on src/ufo/filters/RatioCheck.cc
> +          ref[jobs] = 1.;
You have this but it will never be set because the first if checks for fabs(ref[jobs]) < 1.e-36), plus we would never want to set a value from 0 to 1.

2020-12-11 12:53 UTC, CoryMartin-NOAA commented on test/testinput/qc_ratiocheck.yaml
> +      #obsfile: /scratch1/NCEPDEV/da/Iliana.Genkova/JEDI/tutorial/src/fv3-bundle/ufo/test/testinput/filters/filters_testdata.nc4
No hard coded paths!

2020-12-11 22:47 UTC, LouisKouvaris-NOAA commented on test/testinput/cris_qc_filters.yaml
> +# passedBenchmark: 402   #(m_unittest)
resolved

2020-12-11 22:47 UTC, LouisKouvaris-NOAA commented on test/testinput/qc_ratiocheck.yaml
> +      #obsfile: /scratch1/NCEPDEV/da/Iliana.Genkova/JEDI/tutorial/src/fv3-bundle/ufo/test/testinput/filters/filters_testdata.nc4
resolved

2021-01-15 16:43 UTC, closed without merging